openapi: 3.0.0

info:
  title: Data view pro API
  version: 1.0
  description: This is the API documentation for the Data view pro application
  
paths:
  ### Health check endpoint
  /api/health/:
    get:
      summary: Health check
      tags:
        - Health
      description: Health check endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
